media: assets
content:
  - name: pages
    label: Pages
    type: collection
    path: pages
    filename: 
      template: "{file-name}.md"
      field: true
    view:
      fields: [title, date, file-name]
    fields:
      - name: title
        label: Title
        type: string
      - name: file-name
        label: file-name
        type: string
      - name: date
        label: Publish Date
        type: date
      - name: body
        label: Content
        type: rich-text
      - name: related_page
        type: reference
        options:
          collection: pages
          search: "name,fields.body"