title: Acquisitions Institute at Timberline Lodge
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/AITL_LOGOS_Blue.png
description: A three-day conference focusing on the methods and innovation of building and managing library collections.
show_downloads: false
plugins:
- jekyll-remote-theme
